### ISSUE TITLE
Juniper compatibility

### ISSUE THREAD

**Issue by toxinu** [oppia/xblock#5]
Hi there,

I wanted to know if your xBlock is already Juniper (Python 3 and Django 2.2) compatible and if not, is there any plan to update it for Juniper? Or are you open to contributions?

Thanks.

cc @seanlip

**Comment by seanlip** [comment]
Probably not -- we haven't updated this for a while, and there are no current plans to update it.

I think we won't really be able to accept contributions since we don't have a great mechanism at the moment for testing stuff out. However, you'd be more than welcome to make a fork!

**Comment by toxinu** [comment]
Thanks for your reply @seanlip :)
